### ISSUE TITLE
App crash : java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.

### ISSUE THREAD

**Issue by rucha09** [red5pro/streaming-android#117]
03-16 21:33:24.528 26395-26395/vunya.ic E/AudioRecord: Could not get audio input for record source 1, sample rate 8000, format 0x1, channel mask 0x10, session 580, flags 0
03-16 21:33:24.529 26395-26395/vunya.ic E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
03-16 21:33:24.529 26395-26395/vunya.ic E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
03-16 21:33:24.530 26395-26395/vunya.ic D/AndroidRuntime: Shutting down VM
03-16 21:33:24.531 26395-26395/vunya.ic E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: vunya.ic, PID: 26395
                                                          java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                              at android.media.AudioRecord.startRecording(AudioRecord.java:658)
                                                              at com.red5pro.streaming.media.R5AudioController.b(Unknown Source)
                                                              at com.red5pro.streaming.media.R5AudioController.a(Unknown Source)
                                                              at com.red5pro.streaming.media.a.run(Unknown Source)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by HoldenMills** [comment]
Hello. Please provide our support team with more information by submitting a ticket using this link: https://red5pro.zendesk.com/hc/en-us/requests/new.
Please make sure to provide additional details such as reproduction steps to speed up the process.

**Comment by rucha09** [comment]
@HoldenMills  You can check it here: http://crashes.to/s/e43d38fbe0b

**Comment by HoldenMills** [comment]
Great. In order for us to properly track and investigate your issue, you will need to fill out a support ticket. You can include that link in the ticket. Thanks!
