### ISSUE TITLE
when localrecording video can't play..

### ISSUE THREAD

**Issue by Kaleeswaran-Chellaiah** [red5pro/streaming-android#128]
07-03 06:27:11.729 25200-25200/com.app.touchapp W/System.err: java.lang.IllegalStateException: writeSampleData returned an errorat android.media.MediaMuxer.nativeWriteSampleData(Native Method)at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:675)at com.red5pro.streaming.source.a.a(Unknown Source:87)at com.red5pro.streaming.source.h.ob(Unknown Source:6)at com.red5pro.streaming.source.R5VideoSource.drain(Unknown Source:219)07-03 06:27:11.730 25200-25200/com.app.touchapp W/System.err: at com.red5pro.streaming.source.R5VideoSource.encode(Unknown Source:222)at com.red5pro.streaming.source.R5Camera.onPreviewFrame(Unknown Source:90)at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1361)at android.os.Handler.dispatchMessage(Handler.java:105)at android.os.Looper.loop(Looper.java:164)at android.app.ActivityThread.main(ActivityThread.java:6798)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by HoldenMills** [comment]
Hello. Please provide our support team with more information by submitting a ticket using this link: https://red5pro.zendesk.com/hc/en-us/requests/new.
Please make sure to provide additional details such as reproduction steps to speed up the process.
