### ISSUE TITLE
NoClassDefFoundError Lorg/apache/mina/core/buffer/IoBuffer

### ISSUE THREAD

**Issue by phongbm** [red5pro/streaming-android#65]
I have a problem
_____________________________________
02-20 19:49:15.025 7869-8975/com.phongbm.eg E/AndroidRuntime: FATAL EXCEPTION: Thread-1449
                                                              Process: com.phongbm.eg, PID: 7869
                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/mina/core/buffer/IoBuffer;
                                                                  at com.red5pro.streaming.core.l.a(Unknown Source)
                                                                  at com.red5pro.streaming.R5Stream.write(Unknown Source)
                                                                  at com.red5pro.streaming.source.c.run(Unknown Source)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.mina.core.buffer.IoBuffer" on path: DexPathList[[dex file "/data/data/com.phongbm.eg/files
...
__________________________________________
I was added dependencies
compile 'org.apache.mina:mina-core:3.0.0-M2'
How to fix it?

**Comment by HoldenMills** [comment]
@phongbm My apologies for taking so long to get back to you.  Could you fill out a support ticket so that I can gather all the information I need from you?  Here is the link: https://red5pro.zendesk.com/hc/en-us/requests/new
Thanks, and again, my apologies for the delay.

**Comment by devganiyahitesh1** [comment]
I have a same problem. Any solution here ?

**Comment by HoldenMills** [comment]
There are a few different things that could be causing that issue. Have you taken a look at our [Troubleshooting Guide](https://red5pro.zendesk.com/hc/en-us/articles/115008025448-Troubleshooting-Guide)?  If you are still experiencing problems, please fill out a[ support ticket](https://red5pro.zendesk.com/hc/en-us/articles/115008025448-Troubleshooting-Guide) so that we can more effectively track your issue in our support system.
